# Site settings
title: Disclojures
email: subhashgo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Brain dump. Unedited. You have been warned.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://subhash.github.io/" # the base hostname & protocol for your site
github_username:  subhashgo

# Build settings
markdown: kramdown
kramdown:
  input: GFM
